### ISSUE TITLE
Make variables created using $createVar permanent 

### ISSUE THREAD

**Issue by KASKUSTTV** [aoijs/aoi.js#238]
## Type
- [x] Functions: \<$createVar>
- [ ] Callbacks: \<Callback Name>
- [ ] Handlers: \<Handler Type>
- [ ] Others: \______

## Description
Pls make make it permanent it's very useful for making suggestion system like we will be able to use number is approving suggestion instead of message I'd, example: `<prefix>suggestion accept [number]`. Or just add permanently option to it like `$createVar[varName:varValue;permanent (yes or no)(optional)]`

**Comment by BeastBoyADI** [comment]
U can still make it setting an existing variable instead of creating new

**Comment by USERSATOSHI** [comment]
> 
> 
> ## Type
> - [x] Functions: \<$createVar>
> - [ ] Callbacks: \<Callback Name>
> - [ ] Handlers: \<Handler Type>
> - [ ] Others: \______
> 
> ## Description
> Pls make make it permanent it's very useful for making suggestion system like we will be able to use number is approving suggestion instead of message I'd, example: `<prefix>suggestion accept [number]`. Or just add permanently option to it like `$createVar[varName:varValue;permanent (yes or no)(optional)]`

@KASKUSTTV 
`$createVar` was added because for new variables in `bot.variables` u need to restart the bot

so after `adding the var` in `bot.variables` 
`eval $createVar` so that u can use it **without restart and it will available ij next update**

also 

only way to make it `permanent` is by **removing bot.variables** from aoijs which won't be done
