### ISSUE TITLE
Bug: custom functions return themselves

### ISSUE THREAD

**Issue by papaaj** [aoijs/aoi.js#550]
### Bug Type

Function

### Bugged Function

```js
when you use a custom function (no matter where) it returns the things which you wanted it to return and the function name (for example $functionName)

I use github version of aoi.js if that's important
```

### Version of aoi.js

v6.6.1

### Version of Node.js

v20.10.0 (LTS)

### Excepted Output

custom functions shouldnt return theirselves ($functionName)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Faf4a** [comment]
Custom functions are completely bugged, @USERSATOSHI wanted to rewrite interpreter to fix that. Please bare with him.

**Comment by Leref** [comment]
Wrong, the way it works sufficiently is by adding the create function before loading commands, as well if you use $eval, it will execute twice since it's executing the output + the send message since eval is tricked into thinking it's a message command still. 
This was already resolved with $eval being updated.
